"use client";
import Link from "next/link";
import { T, useLanguage } from "../components/LanguageProvider";
import { phones, whatsappUrl } from "../lib/phones";

export default function Home(){const {lang}=useLanguage();const featured=phones.slice(0,4);return <>
  <section className="storeHero"><div className="heroBlob one"/><div className="heroBlob two"/><div className="wide storeHeroGrid">
    <div className="storeHeroCopy"><span className="shopBadge"><T pt="TECNOLOGIA MAIS PERTO DE SI" en="TECHNOLOGY CLOSER TO YOU" /></span><h1><T pt={<>Encontre o telefone<br/><em>certo para si.</em></>} en={<>Find the right phone<br/><em>for you.</em></>} /></h1><p><T pt="Smartphones seleccionados, atendimento próximo e assistência técnica quando precisar." en="Selected smartphones, personal service and technical support whenever you need it." /></p><div className="actionRow"><Link className="btn blue" href="/telefones"><T pt="Ver telefones" en="View phones" /> <span>→</span></Link><Link className="btn soft" href="/reparacao"><T pt="Reparar telefone" en="Repair phone" /></Link></div><div className="heroAssurance"><span>✓ <T pt="Atendimento pelo WhatsApp" en="WhatsApp assistance" /></span><span>✓ <T pt="Loja em Bela Vista" en="Store in Bela Vista" /></span></div></div>
    <div className="showcase" aria-label={lang==="pt"?"Telefones em exposição":"Phones on display"}><div className="showcaseGlow"/><div className="showPhone phoneBack"><img src={phones[1].image} alt={phones[1].model}/></div><div className="showPhone phoneMain"><img src={phones[0].image} alt={phones[0].model}/><span className="newTag"><T pt="NOVIDADE" en="NEW" /></span></div><div className="showPhone phoneSide"><img src={phones[2].image} alt={phones[2].model}/></div><div className="showPrice"><small><T pt="DISPONÍVEL" en="AVAILABLE" /></small><b><T pt="Consulte o preço" en="Ask for price" /></b><Link href={`/telefones/${phones[0].slug}`}>↗</Link></div></div>
  </div></section>

  <section className="quickShop"><div className="wide"><div className="quickTitle"><b><T pt="O que procura hoje?" en="What are you looking for?" /></b><Link href="/telefones"><T pt="Ver catálogo completo" en="View full catalogue" /> →</Link></div><div className="categoryGrid">{[
    ["/telefones?marca=Apple","◉","iPhone"],["/telefones?marca=Samsung","S","Samsung"],["/telefones?marca=Tecno","T","Tecno"],["/telefones?marca=Infinix","I","Infinix"],["/telefones?marca=Outros","+",lang==="pt"?"Outras marcas":"Other brands"],["/reparacao","⌁",lang==="pt"?"Reparação":"Repair"]
  ].map(c=><Link href={c[0]} key={c[2]}><span>{c[1]}</span><b>{c[2]}</b><i>→</i></Link>)}</div></div></section>

  <section className="featuredStore"><div className="wide"><div className="shopSectionHead"><div><span><T pt="ESCOLHAS DA MM" en="MM PICKS" /></span><h2><T pt="Telefones em destaque" en="Featured phones" /></h2><p><T pt="Modelos seleccionados para diferentes estilos e necessidades." en="Selected models for different styles and needs." /></p></div><Link href="/telefones"><T pt="Ver todos" en="View all" /> →</Link></div><div className="storeProductGrid">{featured.map(p=><article className="storeProduct" key={p.slug}><Link className="storeProductImage" href={`/telefones/${p.slug}`}><span>{p.available?(lang==="pt"?"Disponível":"Available"):(lang==="pt"?"Sob consulta":"Ask us")}</span><img src={p.image} alt={p.model}/></Link><div className="storeProductBody"><small>{p.brand}</small><h3>{p.model}</h3><div className="productMeta"><span>{p.storage}</span><span>{p.condition==="Novo"?(lang==="pt"?"Novo":"New"):(lang==="pt"?"Seminovo":"Pre-owned")}</span></div><strong>{lang==="pt"?p.price:"Ask for price"}</strong><div className="storeActions"><Link href={`/telefones/${p.slug}`}><T pt="Ver detalhes" en="View details" /></Link><a href={whatsappUrl(lang==="pt"?`Olá MM, vi o ${p.model} no website e gostaria de saber mais informações.`:`Hello MM, I saw the ${p.model} on the website and would like more information.`)}>WhatsApp ↗</a></div></div></article>)}</div></div></section>

  <section className="brandShelf"><div className="wide"><span className="sectionLabel"><T pt="ENCONTRE A SUA MARCA" en="FIND YOUR BRAND" /></span><div className="brandRow">{["Apple","Samsung","Tecno","Infinix"].map((b,i)=><Link href={`/telefones?marca=${b}`} key={b}><i>{["A","S","T","I"][i]}</i><b>{b}</b><span>→</span></Link>)}</div></div></section>

  <section className="repairShop"><div className="wide repairShopGrid"><div className="repairPhoto"><img src="https://images.unsplash.com/photo-1621768216002-5ac171876625?auto=format&fit=crop&w=1200&q=90" alt={lang==="pt"?"Reparação de telefone":"Phone repair"}/><div className="repairPhotoBadge"><span>✓</span><div><small><T pt="PRIMEIRO PASSO" en="FIRST STEP" /></small><b><T pt="Diagnóstico técnico" en="Technical diagnostics" /></b></div></div></div><div className="repairShopCopy"><span className="sectionLabel"><T pt="ASSISTÊNCIA TÉCNICA" en="TECHNICAL SUPPORT" /></span><h2><T pt={<>O seu telefone precisa<br/>de <em>reparação?</em></>} en={<>Does your phone need<br/><em>repair?</em></>} /></h2><p><T pt="Conte-nos o problema. Avaliamos o aparelho e explicamos o próximo passo antes da reparação." en="Tell us the issue. We assess the device and explain the next step before repair." /></p><div className="repairChips">{[lang==="pt"?"Ecrã":"Screen",lang==="pt"?"Bateria":"Battery",lang==="pt"?"Carregamento":"Charging",lang==="pt"?"Software":"Software",lang==="pt"?"Câmara":"Camera",lang==="pt"?"Diagnóstico":"Diagnostics"].map(x=><span key={x}>{x}</span>)}</div><Link className="btn blue" href="/reparacao"><T pt="Solicitar reparação" en="Request repair" /> <span>→</span></Link></div></div></section>

  <section className="trustShop"><div className="wide"><div className="shopSectionHead"><div><span><T pt="COMPRE E REPARE COM CONFIANÇA" en="SHOP AND REPAIR WITH CONFIDENCE" /></span><h2><T pt="Por que escolher a MM?" en="Why choose MM?" /></h2></div></div><div className="trustCards">{[["♡","Atendimento próximo","Personal service"],["⌕","Diagnóstico antes da reparação","Diagnosis before repair"],["◇","Telefones seleccionados","Selected phones"],["✆","Contacto rápido pelo WhatsApp","Fast WhatsApp contact"]].map(x=><div key={x[1]}><span>{x[0]}</span><b>{lang==="pt"?x[1]:x[2]}</b></div>)}</div></div></section>
  </>}
