"use client";
import Link from "next/link";
import { T, useLanguage } from "../components/LanguageProvider";
import { phones, whatsappUrl } from "../lib/phones";

export default function Home(){const {lang}=useLanguage();return <>
  <section className="homeHero"><div className="heroAura"/><div className="wide heroLayout"><div className="heroCopy"><span className="kicker"><i/> MM Angola</span><h1><T pt={<>O seu próximo<br/><em>smartphone</em><br/>está na MM.</>} en={<>Your next<br/><em>smartphone</em><br/>is at MM.</>} /></h1><p><T pt="E se o seu actual precisar de ajuda, nós cuidamos dele com atenção e transparência." en="And if your current one needs help, we take care of it with attention and transparency." /></p><div className="actionRow"><Link className="btn blue" href="/telefones"><T pt="Ver telefones" en="View phones" /> <span>→</span></Link><Link className="btn outline" href="/reparacao"><T pt="Reparar meu telefone" en="Repair my phone" /></Link></div><a className="textLink" href={whatsappUrl(lang==="pt"?"Olá MM, gostaria de saber mais sobre os vossos serviços.":"Hello MM, I would like to know more about your services.")}><T pt="Falar agora no WhatsApp" en="Chat now on WhatsApp" /> ↗</a></div><div className="heroProduct"><div className="blueOrbit"/><div className="device"><div className="deviceScreen"><div className="deviceLight"/><img src="/logo-mm.png" alt="MM"/></div></div><div className="heroTag tagOne"><small><T pt="COMPRA" en="SHOP" /></small><b><T pt="Telefones seleccionados" en="Selected smartphones" /></b></div><div className="heroTag tagTwo"><small><T pt="ASSISTÊNCIA" en="SUPPORT" /></small><b><T pt="Reparação especializada" en="Specialist repair" /></b></div></div></div></section>

  <section className="lightSection highlights"><div className="wide highlightGrid">{[["◇","Smartphones seleccionados","Selected smartphones"],["✦","Reparação especializada","Specialist repair"],["◉","Atendimento pelo WhatsApp","WhatsApp assistance"],["⌖","Localização fácil","Easy location"]].map(x=><div key={x[1]}><span>{x[0]}</span><b>{lang==="pt"?x[1]:x[2]}</b></div>)}</div></section>

  <section className="lightSection productPreview"><div className="wide"><div className="sectionIntro darkText"><span className="kicker"><i/> <T pt="Escolhas MM" en="MM picks" /></span><div><h2><T pt={<>Telefones em<br/><em>destaque.</em></>} en={<>Featured<br/><em>phones.</em></>} /></h2><p><T pt="Uma selecção curta para começar. Consulte a disponibilidade e fale directamente connosco." en="A short selection to get you started. Check availability and speak directly with us." /></p></div></div><div className="previewGrid">{phones.slice(0,3).map(p=><article className="lightProduct" key={p.slug}><Link className="lightProductImage" href={`/telefones/${p.slug}`}><img src={p.image} alt={p.model}/></Link><small>{p.brand} · {p.storage}</small><h3>{p.model}</h3><div><b>{p.price}</b><Link href={`/telefones/${p.slug}`}><T pt="Ver detalhes" en="View details" /> →</Link></div></article>)}</div><div className="centerAction"><Link className="btn dark" href="/telefones"><T pt="Ver todos os telefones" en="View all phones" /> <span>→</span></Link></div></div></section>

  <section className="repairTeaser"><div className="wide split"><div className="repairArt"><div className="scanDevice"><span>MM</span><i/></div><div className="diagCard"><small><T pt="DIAGNÓSTICO" en="DIAGNOSTICS" /></small><b><T pt="Análise técnica" en="Technical analysis" /></b></div></div><div className="repairTeaserCopy"><span className="kicker"><i/> <T pt="Assistência técnica" en="Technical support" /></span><h2><T pt={<>O seu telefone<br/>apresentou <em>problema?</em></>} en={<>Is there a <em>problem</em><br/>with your phone?</>} /></h2><p><T pt="Ecrã, bateria, conector, software e muito mais. Começamos sempre por entender o problema." en="Screen, battery, charging port, software and more. We always start by understanding the problem." /></p><Link className="btn blue" href="/reparacao"><T pt="Conhecer serviços de reparação" en="Explore repair services" /> <span>→</span></Link></div></div></section>

  <section className="wide homeContact"><div><span className="kicker"><i/> WhatsApp</span><h2><T pt={<>Pronto para falar<br/>com a <em>MM?</em></>} en={<>Ready to talk<br/>to <em>MM?</em></>} /></h2></div><div><p><T pt="Pergunte por um telefone, explique o problema do seu aparelho ou peça a nossa localização." en="Ask about a phone, explain your device issue or request our location." /></p><a className="btn white" href={whatsappUrl(lang==="pt"?"Olá MM, vim pelo website e gostaria de falar convosco.":"Hello MM, I came from the website and would like to speak with you.")}><T pt="Iniciar conversa" en="Start conversation" /> ↗</a></div></section>
  </>}
